dataset: inpainted
labels: original
image_size: 224
clip_pretrained_model: openai/clip-vit-base-patch32
caption_mode: none
multilingual_tokenizer_path: none
freeze_image_encoder: true
freeze_text_encoder: true
batch_size: 16
lr: 1.0e-05
weight_decay: 0.0001
gpus: '0'
max_epochs: 1
log_every_n_steps: 10
limit_train_batches: 1.0
limit_val_batches: 1.0
use_pretrained_map: false
local_pretrained_weights: null
wandb_mode: offline
wandb_timeout: 180
wandb_base_url: https://api.wandb.ai
